hanbellgp/Hanbell-EAP

EFGP-ejb/src/java/cn/hanbell/oa/ejb/BXDDetail01Bean.java
EFGP-ejb/src/java/cn/hanbell/oa/ejb/BxdBean.java
EFGP-ejb/src/java/cn/hanbell/oa/entity/BXDDetail01.java
EFGP-ejb/src/java/cn/hanbell/oa/entity/BXDDetail02.java
EFGP-ejb/src/java/cn/hanbell/oa/entity/Bxd.java
ERP-ejb/nbproject/private/private.xml
ERP-ejb/src/java/cn/hanbell/erp/comm/SuperEJBForERP.java
ERP-ejb/src/java/cn/hanbell/erp/ejb/ApmpadBean.java
ERP-ejb/src/java/cn/hanbell/erp/ejb/ApmpayBean.java
ERP-ejb/src/java/cn/hanbell/erp/ejb/ApmsysBean.java
ERP-ejb/src/java/cn/hanbell/erp/entity/Apmpad.java
ERP-ejb/src/java/cn/hanbell/erp/entity/ApmpadPK.java
ERP-ejb/src/java/cn/hanbell/erp/entity/Apmpay.java
ERP-ejb/src/java/cn/hanbell/erp/entity/ApmpayPK.java
Hanbell-JWS/src/java/cn/hanbell/jws/SHBERPWebService.java

避免XA事务冲突,修改获取EntityManager方法,放弃setEntityManagerByCompany,改为setCompany

修改SuperEJBForERP

---

EFGP-ejb/src/java/cn/hanbell/oa/entity/HKYX006.java
ERP-ejb/src/conf/persistence.xml
ERP-ejb/src/java/cn/hanbell/erp/comm/SuperEJBForERP.java
ERP-ejb/src/java/cn/hanbell/erp/ejb/ApmpayBean.java
ERP-ejb/src/java/cn/hanbell/erp/ejb/CdrcusBean.java
ERP-ejb/src/java/cn/hanbell/erp/ejb/PurvdrBean.java
Hanbell-JRS/src/java/cn/hanbell/jrs/CdrcusFacadeREST.java

EFGP使用XA事务 不再使用syncEFGPBean进行非XA更新

增加SDERP连接 EFGP使用XA事务

---

EFGP-ejb/src/java/cn/hanbell/oa/entity/HKYX007.java
EFGP-ejb/src/java/cn/hanbell/oa/entity/HZCW028reDetail.java
ERP-ejb/src/java/cn/hanbell/erp/ejb/AccrnoBean.java
ERP-ejb/src/java/cn/hanbell/erp/ejb/ApmpayBean.java
ERP-ejb/src/java/cn/hanbell/erp/ejb/BudgetDetailBean.java
ERP-ejb/src/java/cn/hanbell/erp/ejb/MiscodeBean.java
ERP-ejb/src/java/cn/hanbell/erp/entity/Miscode.java

解决借支归还单预算预扣金额还原错误Bug
解决apmpad未设置员工姓名Bug

配合EFGP上线发布

---

ERP-ejb/src/java/cn/hanbell/erp/ejb/PurvdrBean.java

优化分公司新增厂商时资料同步功能

---

ERP-ejb/src/java/cn/hanbell/erp/ejb/ApmpayBean.java

借支归还单抛砖ERP 处理部门修改

---

EFGP-ejb/src/java/cn/hanbell/oa/entity/HZJS034.java
EFGP-ejb/src/java/cn/hanbell/oa/entity/HZJS034Detail.java
EFGP-ejb/src/java/cn/hanbell/oa/entity/SHBERPINV140Detail.java
ERP-ejb/src/java/cn/hanbell/erp/ejb/PurhaskBean.java
Hanbell-JWS/src/java/cn/hanbell/jws/SHBERPWebService.java

修改请购抛转webservice方法名称

---

ERP-ejb/src/java/cn/hanbell/erp/ejb/InvmasBean.java
ERP-ejb/src/java/cn/hanbell/erp/ejb/PurhaskBean.java

请购关于不同公司别抛转的修复

---

EFGP-ejb/src/java/cn/hanbell/oa/ejb/ProcessInstanceBean.java
EFGP-ejb/src/java/cn/hanbell/oa/entity/HZJS034Detail.java
ERP-ejb/src/java/cn/hanbell/erp/ejb/InvmasBean.java
Hanbell-RPT/src/java/cn/hanbell/rpt/control/ReportManagedBean.java
Hanbell-RPT/web/rpt/hzcw027.rptdesign

OA打印收款凭单格式，件号新增换算率

---

EFGP-ejb/src/java/cn/hanbell/oa/ejb/HZCW028Bean.java

CRM费用在OA合并后 更新和回写方法修改

---

EFGP-ejb/src/java/cn/hanbell/oa/ejb/HZCW033Bean.java
ERP-ejb/src/java/cn/hanbell/erp/ejb/InvmasBean.java
ERP-ejb/src/java/cn/hanbell/erp/ejb/PurhaskBean.java
ERP-ejb/src/java/cn/hanbell/erp/entity/Invmas.java
Hanbell-JWS/src/java/cn/hanbell/jws/SHBERPWebService.java

请购，件号修改，借支归还CRM费用新增

---

ERP-ejb/src/java/cn/hanbell/erp/ejb/CdrcusBean.java
ERP-ejb/src/java/cn/hanbell/erp/ejb/PurhaskBean.java

 采购抛转号修改，客户地址修改

---

EFGP-ejb/src/java/cn/hanbell/oa/ejb/HKFW005Bean.java
EFGP-ejb/src/java/cn/hanbell/oa/ejb/HKFW005DetailBean.java
EFGP-ejb/src/java/cn/hanbell/oa/ejb/ProcessInstanceBean.java
EFGP-ejb/src/java/cn/hanbell/oa/entity/HKFW005.java
EFGP-ejb/src/java/cn/hanbell/oa/entity/HKFW005Detail.java
EFGP-ejb/src/java/cn/hanbell/oa/entity/ProcessInstance.java
Hanbell-RPT/src/java/cn/hanbell/efgp/rpt/HKFW005Report.java
Hanbell-RPT/web/rpt/hkfw005.rptdesign

服务工作支援单打印功能

---

EFGP-ejb/src/java/cn/hanbell/oa/entity/HKFW006Inv310.java
ERP-ejb/src/java/cn/hanbell/erp/ejb/CdrbrhadBean.java
ERP-ejb/src/java/cn/hanbell/erp/ejb/InvhadBean.java
ERP-ejb/src/java/cn/hanbell/erp/entity/Cdrbrhad.java
ERP-ejb/src/java/cn/hanbell/erp/entity/Cdrlnhad.java

C1491代码合并修改

---

ERP-ejb/src/java/cn/hanbell/erp/ejb/InvmasBean.java

件号转移品号大类关联

---

EFGP-ejb/src/java/cn/hanbell/oa/model/SHBERPINV325DetailModel.java
EFGP-ejb/src/java/cn/hanbell/oa/model/SHBERPINV325Model.java
Hanbell-JWS/src/java/cn/hanbell/jws/TimerBean.java

大批领料单关键字修正

---

EFGP-ejb/src/java/cn/hanbell/oa/ejb/WARMI05Bean.java

录入库存交易单反写页面状态码

---

ERP-ejb/src/java/cn/hanbell/erp/ejb/InvhadBean.java
Hanbell-Admin/src/java/cn/hanbell/eap/control/UserManagedBean.java
Hanbell-Admin/src/java/cn/hanbell/eap/web/FormMulti2Bean.java
Hanbell-Admin/src/java/cn/hanbell/eap/web/FormMulti3Bean.java
Hanbell-Admin/src/java/cn/hanbell/eap/web/FormMultiBean.java
Hanbell-Admin/src/java/cn/hanbell/eap/web/FormSingleBean.java
Hanbell-Admin/src/java/cn/hanbell/eap/web/SuperMulti3Bean.java
Hanbell-Admin/src/java/cn/hanbell/eap/web/SuperMultiBean.java
Hanbell-Admin/src/java/cn/hanbell/eap/web/SuperQueryBean.java
Hanbell-Admin/src/java/cn/hanbell/eap/web/SuperSingleBean.java

Bug修正和代码优化

---

ERP-ejb/src/java/cn/hanbell/erp/ejb/InvmasBean.java

件号新增改善运行时错误

---

EFGP-ejb/src/java/cn/hanbell/oa/ejb/HKJH001Bean.java
EFGP-ejb/src/java/cn/hanbell/oa/ejb/HKJH001serialBean.java
EFGP-ejb/src/java/cn/hanbell/oa/entity/HKJH001.java
EFGP-ejb/src/java/cn/hanbell/oa/entity/HKJH001serial.java

合同审批单合同编号生成及反写到OA中

---

Hanbell-JWS/src/java/cn/hanbell/jws/EAPWebService.java

合同审核表单web service

---

EFGP-ejb/src/java/cn/hanbell/oa/entity/HKJH001.java

C1587 合同审批单实体类修正

---

EFGP-ejb/src/java/cn/hanbell/oa/entity/HKJH001.java

合同审核单实体类修改

---

Hanbell-JWS/src/java/cn/hanbell/jws/EAPWebService.java

CRM 同步件号修正

---

ERP-ejb/src/java/cn/hanbell/erp/ejb/CdrlnhadBean.java

抛转CDRN20 批号管理

---

EFGP-ejb/src/java/cn/hanbell/oa/ejb/SERI12Bean.java
Hanbell-JWS/nbproject/private/private.xml

CRM反写结案时间，结案人员

---

Hanbell-RPT/web/rpt/hzcw034.rptdesign

资产报废处置单打印格式调整

---

Hanbell-RPT/web/rpt/hzcw034.rptdesign

资产报废处置打印格式调整

---

Hanbell-RPT/web/rpt/hzcw034.rptdesign

资产报废处置单打印格式调整支持15行+

---

EFGP-ejb/src/java/cn/hanbell/oa/ejb/VHTV002Bean.java
Hanbell-RPT/web/rpt/hkgl039.rptdesign

越南借支单逻辑调整及废品出售明细打印调整

---

EFGP-ejb/src/java/cn/hanbell/oa/ejb/VHTV002Bean.java

越南借支归还单逻辑调整
